server:
  address: localhost
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    com.adi.docflow: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
    username: docflow_app
    password: Docflow@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: app
        jdbc.time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect

  flyway:
    enabled: true
    schemas: app
    create-schemas: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: adisolutionsmestre@gmail.com
    password: wlzk yaka rzky krck
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: "47c494cec5707734249282b70b949039"   # >=32 bytes (ok)
    exp-minutes: 120          # duração do token JWT em minutos (tempo de sessão)
    clock-skew-seconds: 30    # tolerância de relógio entre servidor/cliente

app:
  auth:
    registration:
      dba-token: "TOKEN_DBA_SECRETO"
      admin-token: "TOKEN_ADMIN_SECRETO"
      resource-token: "TOKEN_RESOURCE_SECRETO"
      user-token: "TOKEN_USER_SECRETO"
  frontend:
    reset-url: "http://localhost:5173/reset-access"

